#!/bin/bash

# Les Deux Palais - Quick Start Guide
# Ce script vous aide à démarrer le site localement

echo "🍽️  Les Deux Palais Restaurant Website"
echo "======================================"
echo ""
echo "📂 Localisation du projet:"
echo "   /home/nasa/Documents/prj/rayan/les-deux-palais/"
echo ""
echo "🌐 Options pour voir le site:"
echo ""
echo "1️⃣  OPTION 1 - Ouvrir avec votre navigateur:"
echo "   Ouvrez le fichier: index.html"
echo "   Clic droit > Ouvrir avec > Navigateur"
echo ""
echo "2️⃣  OPTION 2 - Serveur local avec Python:"
echo "   cd /home/nasa/Documents/prj/rayan/les-deux-palais"
echo "   python3 -m http.server 8000"
echo "   Puis: http://localhost:8000"
echo ""
echo "3️⃣  OPTION 3 - Live Server (VS Code):"
echo "   Installez l'extension 'Live Server'"
echo "   Clic droit sur index.html > Open with Live Server"
echo ""
echo "4️⃣  OPTION 4 - Site en ligne (déjà déployé):"
echo "   🌍 https://les-deux-palais.vercel.app/"
echo ""
echo "✨ Fichiers du projet:"
echo "   📄 index.html  - Page principale"
echo "   🎨 style.css   - Styles et animations"
echo "   ⚡ script.js   - Interactions JavaScript"
echo "   📖 README.md   - Documentation complète"
echo ""
echo "📞 Infos du restaurant:"
echo "   📍 14 Av. Ouarzazate, Rabat"
echo "   ☎️  0661-068852"
echo "   ⏰ 11:00 - 01:00 (tous les jours)"
echo "   ⭐ 4.0★ / 1,668 avis"
echo ""
echo "======================================"
